import type { MenuCategoryDocument } from "../types";
import { keyed, unsplash } from "./helpers";

/** Generated from design/project/shared/data.js (itemsByCategory). */
export const menuCategories: MenuCategoryDocument[] = [
  {
    _id: "menuCategory-breakfast",
    _type: "menuCategory",
    title: "Breakfast",
    slug: { _type: "slug", current: "breakfast" },
    description: "From dawn croissants to skillet scrambles.",
    tone: "gold",
    orderRank: 1,
    items: keyed("breakfast", [
      {
        name: "Cinnamon French Toast",
        price: 11.95,
        calories: 640,
        description: "Thick-cut Texas toast soaked in vanilla custard, griddled, dusted with cinnamon sugar, served with warm maple syrup.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Honey Lavender Latte","Fresh OJ"],
        image: unsplash("photo-1484723091739-30a097e8f929", 1200, "Cinnamon French Toast"),
      },
      {
        name: "Hearth Skillet",
        price: 12.95,
        calories: 780,
        description: "Yukon potatoes, three-cheese scramble, applewood bacon, charred tomato, sourdough toast.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Drip Coffee","Berry Smoothie"],
        image: unsplash("photo-1525351484163-7529414344d8", 1200, "Hearth Skillet"),
      },
      {
        name: "Almond Pull-Apart",
        price: 6.25,
        calories: 520,
        description: "Brioche pulled-apart with almond cream, baked golden, finished with sliced almonds and pearl sugar.",
        allergens: ["egg","gluten","dairy","tree nut"],
        pairsWith: ["Cortado","Earl Grey"],
        image: unsplash("photo-1509365465985-25d11c17e812", 1200, "Almond Pull-Apart"),
      },
      {
        name: "Sausage Egg Croissant",
        price: 8.95,
        calories: 610,
        description: "House croissant, breakfast sausage, two-egg scramble, sharp cheddar, peppery aioli.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Cold Brew"],
        image: unsplash("photo-1623334044303-241021148842", 1200, "Sausage Egg Croissant"),
      },
      {
        name: "Berry Yogurt Bowl",
        price: 7.5,
        calories: 340,
        description: "Whole-milk yogurt, in-season berries, toasted oat granola, wildflower honey.",
        allergens: ["dairy","oat"],
        pairsWith: ["Green Smoothie"],
        image: unsplash("photo-1488477181946-6428a0291777", 1200, "Berry Yogurt Bowl"),
      },
      {
        name: "Avocado Sourdough",
        price: 9.95,
        calories: 430,
        description: "Country sourdough, smashed avocado, soft-boiled egg, espelette, lemon, herbs.",
        allergens: ["egg","gluten"],
        pairsWith: ["Flat White"],
        image: unsplash("photo-1588137378633-dea1336ce1e2", 1200, "Avocado Sourdough"),
      },
    ]),
  },
  {
    _id: "menuCategory-breads",
    _type: "menuCategory",
    title: "Artisan Breads",
    slug: { _type: "slug", current: "breads" },
    description: "Hearth-baked daily. Long-fermented. Honest.",
    tone: "red",
    orderRank: 2,
    items: keyed("breads", [
      {
        name: "Country Sourdough Boule",
        price: 8.5,
        calories: 120,
        description: "Open crumb, blistered crust, 36-hour cold ferment with our 14-year-old levain.",
        allergens: ["gluten"],
        pairsWith: ["Salted Butter","Olive Oil + Sea Salt"],
        image: unsplash("photo-1586444248902-2f64eddc13df", 1200, "Country Sourdough Boule"),
      },
      {
        name: "Seeded Rye",
        price: 8.95,
        calories: 140,
        description: "Caraway, fennel, and toasted sunflower seeds in a dense crumb.",
        allergens: ["gluten","seed"],
        pairsWith: ["Sharp Cheddar"],
        image: unsplash("photo-1568254183919-78a4f43a2877", 1200, "Seeded Rye"),
      },
      {
        name: "Honey Wheat",
        price: 7.5,
        calories: 135,
        description: "Soft sandwich loaf, sweetened lightly with clover honey.",
        allergens: ["gluten"],
        pairsWith: ["Turkey + Avocado"],
        image: unsplash("photo-1568051243851-f9b136146e97", 1200, "Honey Wheat"),
      },
      {
        name: "Olive & Rosemary Focaccia",
        price: 9.5,
        calories: 180,
        description: "High-hydration focaccia, Castelvetrano olives, fresh rosemary, finishing oil.",
        allergens: ["gluten"],
        pairsWith: ["Tomato Bisque"],
        image: unsplash("photo-1568471173242-461f0a730452", 1200, "Olive & Rosemary Focaccia"),
      },
      {
        name: "Harvest Grain",
        price: 8.25,
        calories: 150,
        description: "Five-grain blend, oats on top, slow-fermented for a deep, nutty flavor.",
        allergens: ["gluten","oat"],
        pairsWith: ["Egg Salad"],
        image: unsplash("photo-1509440159596-0249088772ff", 1200, "Harvest Grain"),
      },
      {
        name: "Brioche Loaf",
        price: 9.95,
        calories: 160,
        description: "Buttery, rich, pillowy. Sliced for French toast or torn for the table.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Strawberry Jam"],
        image: unsplash("photo-1568254183919-78a4f43a2877", 1200, "Brioche Loaf"),
      },
    ]),
  },
  {
    _id: "menuCategory-sandwiches",
    _type: "menuCategory",
    title: "Sandwiches",
    slug: { _type: "slug", current: "sandwiches" },
    description: "Stacked on our breads, made to order.",
    tone: "gold",
    orderRank: 3,
    items: keyed("sandwiches", [
      {
        name: "The Kneaders Turkey",
        price: 13.5,
        calories: 720,
        description: "Roasted turkey, applewood bacon, avocado, tomato, butter lettuce, cranberry aioli on harvest grain.",
        allergens: ["gluten","egg"],
        pairsWith: ["Tomato Basil Bisque"],
        image: unsplash("photo-1528735602780-2552fd46c7af", 1200, "The Kneaders Turkey"),
      },
      {
        name: "Roast Beef + Cheddar",
        price: 13.95,
        calories: 740,
        description: "Slow-roasted beef, sharp cheddar, caramelized onion, horseradish cream on seeded rye.",
        allergens: ["gluten","dairy"],
        pairsWith: ["Potato Leek Soup"],
        image: unsplash("photo-1565299507177-b0ac66763828", 1200, "Roast Beef + Cheddar"),
      },
      {
        name: "Caprese Pesto",
        price: 12.5,
        calories: 620,
        description: "Heirloom tomato, fresh mozzarella, basil pesto, balsamic glaze on focaccia.",
        allergens: ["gluten","dairy","tree nut"],
        pairsWith: ["Spring Salad"],
        image: unsplash("photo-1592415486689-125cbbfcbee2", 1200, "Caprese Pesto"),
      },
      {
        name: "Chicken Salad Croissant",
        price: 11.95,
        calories: 580,
        description: "Roast chicken, celery, grapes, toasted almonds, herb mayo on a flaky croissant.",
        allergens: ["egg","gluten","dairy","tree nut"],
        pairsWith: ["Iced Tea"],
        image: unsplash("photo-1539252554453-80ab65ce3586", 1200, "Chicken Salad Croissant"),
      },
      {
        name: "Grilled Cheese, Three Ways",
        price: 10.95,
        calories: 680,
        description: "Sharp cheddar, gruyère, fontina on country sourdough, griddled in salted butter.",
        allergens: ["gluten","dairy"],
        pairsWith: ["Tomato Basil Bisque"],
        image: unsplash("photo-1528736235302-52922df5c122", 1200, "Grilled Cheese, Three Ways"),
      },
      {
        name: "Garden Veg",
        price: 11.5,
        calories: 540,
        description: "Roasted peppers, cucumber, sprouts, hummus, herb-whipped feta on multigrain.",
        allergens: ["gluten","dairy","sesame"],
        pairsWith: ["Lemon Quinoa Salad"],
        image: unsplash("photo-1606755962773-d324e0a13086", 1200, "Garden Veg"),
      },
    ]),
  },
  {
    _id: "menuCategory-soups",
    _type: "menuCategory",
    title: "Soups",
    slug: { _type: "slug", current: "soups" },
    description: "A rotating schedule. Always with bread.",
    tone: "sage",
    orderRank: 4,
    items: keyed("soups", [
      {
        name: "Tomato Basil Bisque",
        price: 7.95,
        calories: 310,
        description: "Slow-roasted tomatoes, fresh basil, a touch of cream. Served with our focaccia.",
        allergens: ["dairy","gluten"],
        pairsWith: ["Grilled Cheese"],
        image: unsplash("photo-1547592180-85f173990554", 1200, "Tomato Basil Bisque"),
      },
      {
        name: "Potato Leek",
        price: 7.5,
        calories: 340,
        description: "Yukon potatoes, leeks, thyme, finished with crème fraîche.",
        allergens: ["dairy"],
        pairsWith: ["Country Sourdough"],
        image: unsplash("photo-1604152135912-04a022e23696", 1200, "Potato Leek"),
      },
      {
        name: "White Bean + Kale",
        price: 7.95,
        calories: 280,
        description: "Cannellini beans, lacinato kale, garlic, parmesan rind, lemon.",
        allergens: ["dairy"],
        pairsWith: ["Seeded Rye"],
        image: unsplash("photo-1604152135912-04a022e23696", 1200, "White Bean + Kale"),
      },
      {
        name: "Chicken Wild Rice",
        price: 8.25,
        calories: 380,
        description: "Pulled chicken, wild rice, root vegetables, sage cream.",
        allergens: ["dairy"],
        pairsWith: ["Honey Wheat"],
        image: unsplash("photo-1547592180-85f173990554", 1200, "Chicken Wild Rice"),
      },
      {
        name: "Roasted Cauliflower",
        price: 7.5,
        calories: 240,
        description: "Charred cauliflower, brown butter, toasted almonds, parsley oil.",
        allergens: ["dairy","tree nut"],
        pairsWith: ["Garden Veg Sandwich"],
        image: unsplash("photo-1604152135912-04a022e23696", 1200, "Roasted Cauliflower"),
      },
    ]),
  },
  {
    _id: "menuCategory-salads",
    _type: "menuCategory",
    title: "Salads",
    slug: { _type: "slug", current: "salads" },
    description: "Crisp, seasonal, and dressed in-house.",
    tone: "sage",
    orderRank: 5,
    items: keyed("salads", [
      {
        name: "Spring Garden",
        price: 11.5,
        calories: 340,
        description: "Butter lettuce, snap peas, radish, soft herbs, lemon vinaigrette.",
        allergens: [],
        pairsWith: ["Country Sourdough"],
        image: unsplash("photo-1512621776951-a57141f2eefd", 1200, "Spring Garden"),
      },
      {
        name: "Harvest Grain Bowl",
        price: 13.5,
        calories: 520,
        description: "Farro, roasted squash, kale, dried cranberry, pumpkin seeds, maple-tahini.",
        allergens: ["gluten","seed"],
        pairsWith: ["Seeded Rye"],
        image: unsplash("photo-1543339308-43e59d6b73a6", 1200, "Harvest Grain Bowl"),
      },
      {
        name: "Caesar, Properly",
        price: 11.95,
        calories: 480,
        description: "Whole leaves of romaine, parmesan, anchovy croutons, classic dressing.",
        allergens: ["egg","fish","dairy","gluten"],
        pairsWith: ["Roasted Chicken"],
        image: unsplash("photo-1550304943-4f24f54ddde9", 1200, "Caesar, Properly"),
      },
      {
        name: "Cobb",
        price: 13.95,
        calories: 640,
        description: "Romaine, blue cheese, bacon, soft egg, avocado, tomato, red wine vinaigrette.",
        allergens: ["egg","dairy"],
        pairsWith: ["Brioche Toast"],
        image: unsplash("photo-1546069901-ba9599a7e63c", 1200, "Cobb"),
      },
    ]),
  },
  {
    _id: "menuCategory-pastries",
    _type: "menuCategory",
    title: "Pastries & Desserts",
    slug: { _type: "slug", current: "pastries" },
    description: "Laminated, glazed, and cooled on the rack.",
    tone: "red",
    orderRank: 6,
    items: keyed("pastries", [
      {
        name: "Chocolate Croissant",
        price: 4.5,
        calories: 380,
        description: "Three-day lamination, dark chocolate batons, brushed with butter and finished raw.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Cortado"],
        image: unsplash("photo-1623334044303-241021148842", 1200, "Chocolate Croissant"),
      },
      {
        name: "Lemon Tart",
        price: 5.5,
        calories: 340,
        description: "Sablé crust, Meyer lemon curd, torched meringue.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Earl Grey"],
        image: unsplash("photo-1519915028121-7d3463d20b13", 1200, "Lemon Tart"),
      },
      {
        name: "Cardamom Knot",
        price: 4.95,
        calories: 320,
        description: "Brioche knot, brown butter and cardamom sugar, pearl sugar finish.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Drip Coffee"],
        image: unsplash("photo-1486427944299-d1955d23e34d", 1200, "Cardamom Knot"),
      },
      {
        name: "Pistachio Financier",
        price: 4.25,
        calories: 280,
        description: "Brown butter, pistachio flour, almond, lightly bitter, deeply nutty.",
        allergens: ["egg","dairy","tree nut"],
        pairsWith: ["Espresso"],
        image: unsplash("photo-1481391319762-47dff72954d9", 1200, "Pistachio Financier"),
      },
      {
        name: "Berry Galette",
        price: 5.95,
        calories: 420,
        description: "Free-form pie crust, in-season berries, vanilla sugar, demerara crunch.",
        allergens: ["gluten","dairy"],
        pairsWith: ["Vanilla Bean Latte"],
        image: unsplash("photo-1488477181946-6428a0291777", 1200, "Berry Galette"),
      },
      {
        name: "Brown Butter Cookie",
        price: 3.5,
        calories: 240,
        description: "Toasted milk solids, sea salt, dark brown sugar — chewy in the middle.",
        allergens: ["egg","gluten","dairy"],
        pairsWith: ["Whole Milk"],
        image: unsplash("photo-1499636136210-6f4ee915583e", 1200, "Brown Butter Cookie"),
      },
    ]),
  },
  {
    _id: "menuCategory-coffee",
    _type: "menuCategory",
    title: "Coffee & Espresso",
    slug: { _type: "slug", current: "coffee" },
    description: "Direct-trade beans, pulled by hand.",
    tone: "blue",
    orderRank: 7,
    items: keyed("coffee", [
      {
        name: "Drip Coffee",
        price: 3.25,
        calories: 5,
        description: "Single-origin daily rotation, brewed on a precision batch machine.",
        allergens: [],
        pairsWith: ["Brown Butter Cookie"],
        image: unsplash("photo-1495474472287-4d71bcdd2085", 1200, "Drip Coffee"),
      },
      {
        name: "Cortado",
        price: 4.25,
        calories: 60,
        description: "Equal parts espresso and steamed whole milk, served in glass.",
        allergens: ["dairy"],
        pairsWith: ["Almond Pull-Apart"],
        image: unsplash("photo-1561882468-9110e03e0f78", 1200, "Cortado"),
      },
      {
        name: "Honey Lavender Latte",
        price: 5.75,
        calories: 180,
        description: "Double espresso, steamed milk, house lavender-honey syrup, dried bud.",
        allergens: ["dairy"],
        pairsWith: ["Pistachio Financier"],
        image: unsplash("photo-1561882468-9110e03e0f78", 1200, "Honey Lavender Latte"),
      },
      {
        name: "Cold Brew",
        price: 4.5,
        calories: 5,
        description: "18-hour steeped, served over a single large rock.",
        allergens: [],
        pairsWith: ["Cardamom Knot"],
        image: unsplash("photo-1517701604599-bb29b565090c", 1200, "Cold Brew"),
      },
      {
        name: "Maple Oat Latte",
        price: 5.5,
        calories: 160,
        description: "Espresso, steamed oat milk, Vermont maple, finishing salt.",
        allergens: ["oat"],
        pairsWith: ["Brown Butter Cookie"],
        image: unsplash("photo-1572442388796-11668a67e53d", 1200, "Maple Oat Latte"),
      },
      {
        name: "Espresso",
        price: 3.5,
        calories: 5,
        description: "Two pulls, ristretto-leaning, served with a sparkling water.",
        allergens: [],
        pairsWith: ["Lemon Tart"],
        image: unsplash("photo-1510707577719-ae7c14805e3a", 1200, "Espresso"),
      },
    ]),
  },
  {
    _id: "menuCategory-smoothies",
    _type: "menuCategory",
    title: "Smoothies",
    slug: { _type: "slug", current: "smoothies" },
    description: "Whole-fruit, never from concentrate.",
    tone: "blue",
    orderRank: 8,
    items: keyed("smoothies", [
      {
        name: "Strawberry Banana",
        price: 6.5,
        calories: 280,
        description: "Whole strawberries, banana, vanilla yogurt, a touch of honey.",
        allergens: ["dairy"],
        pairsWith: ["Avocado Sourdough"],
        image: unsplash("photo-1502741224143-90386d7f8c82", 1200, "Strawberry Banana"),
      },
      {
        name: "Green Garden",
        price: 6.95,
        calories: 240,
        description: "Spinach, banana, mango, ginger, lemon, coconut water.",
        allergens: [],
        pairsWith: ["Berry Yogurt Bowl"],
        image: unsplash("photo-1610970881699-44a5587cabec", 1200, "Green Garden"),
      },
      {
        name: "Wildberry",
        price: 6.5,
        calories: 300,
        description: "Blueberry, blackberry, raspberry, apple juice, vanilla.",
        allergens: [],
        pairsWith: ["Brioche Toast"],
        image: unsplash("photo-1553530666-ba11a7da3888", 1200, "Wildberry"),
      },
    ]),
  },
  {
    _id: "menuCategory-kids",
    _type: "menuCategory",
    title: "Kids Meals",
    slug: { _type: "slug", current: "kids" },
    description: "Half portions. Whole smiles.",
    tone: "rust",
    orderRank: 9,
    items: keyed("kids", [
      {
        name: "Half PB&J",
        price: 5.95,
        calories: 340,
        description: "House grape jelly + crunchy peanut butter on honey wheat. Apple slices on the side.",
        allergens: ["peanut","gluten"],
        pairsWith: ["Whole Milk"],
        image: unsplash("photo-1528736235302-52922df5c122", 1200, "Half PB&J"),
      },
      {
        name: "Mini Mac + Cheese",
        price: 6.5,
        calories: 420,
        description: "Cavatappi, three-cheese, toasted breadcrumb top.",
        allergens: ["gluten","dairy"],
        pairsWith: ["Apple Juice"],
        image: unsplash("photo-1568901346375-23c9450c58cd", 1200, "Mini Mac + Cheese"),
      },
      {
        name: "Kids Grilled Cheese",
        price: 5.5,
        calories: 380,
        description: "American + cheddar on country sourdough, cut into four.",
        allergens: ["gluten","dairy"],
        pairsWith: ["Tomato Bisque"],
        image: unsplash("photo-1528736235302-52922df5c122", 1200, "Kids Grilled Cheese"),
      },
    ]),
  },
  {
    _id: "menuCategory-beverages",
    _type: "menuCategory",
    title: "Beverages",
    slug: { _type: "slug", current: "beverages" },
    description: "Lemonades, teas, and the long pour.",
    tone: "blue",
    orderRank: 10,
    items: keyed("beverages", [
      {
        name: "Lavender Lemonade",
        price: 4.25,
        calories: 140,
        description: "Pressed lemon, lavender simple, soda or still.",
        allergens: [],
        pairsWith: ["Lemon Tart"],
        image: unsplash("photo-1556679343-c7306c1976bc", 1200, "Lavender Lemonade"),
      },
      {
        name: "Sparkling Hibiscus",
        price: 4.5,
        calories: 110,
        description: "Hibiscus tea, lime, agave, soda. Pink and not-too-sweet.",
        allergens: [],
        pairsWith: ["Caprese Pesto"],
        image: unsplash("photo-1558640476-437a2b9438a2", 1200, "Sparkling Hibiscus"),
      },
      {
        name: "Iced Earl Grey",
        price: 3.95,
        calories: 5,
        description: "Brewed strong, poured over ice, optional vanilla cream.",
        allergens: [],
        pairsWith: ["Brown Butter Cookie"],
        image: unsplash("photo-1576092768241-dec231879fc3", 1200, "Iced Earl Grey"),
      },
    ]),
  },
];
