import type { PostDocument } from "../types";
import { portableText, unsplash } from "./helpers";

const slug = (current: string) => ({ _type: "slug" as const, current });

export const posts: PostDocument[] = [
  {
    _id: "post-hand-shape-boule",
    _type: "post",
    title: "Why we still hand-shape every boule",
    slug: slug("hand-shape-boule"),
    tag: "Story",
    readTime: "7 min",
    publishedAt: "2026-04-03",
    author: "Inés Marchetti, Head Baker",
    authorRole: "Contributor",
    excerpt:
      "Speed and softness are not the same thing. A note from our head baker on the math of patience.",
    image: unsplash("photo-1568051243851-f9b136146e97", 1600, "Baker shaping a boule"),
    body: portableText("boule", [
      ["lede", "Speed and softness are not the same thing. A note from our head baker on the math of patience, the bench, and why our 412 hands won't be replaced by a divider."],
      ["normal", "There is a machine that will divide and round a piece of dough faster than you can read this sentence. We don't own one. Not because we can't afford it — we could, easily, ten times over — but because the dough doesn't want it."],
      ["normal", "What a divider does, mechanically, is press a piston down through a chamber of fermented dough and chop it into equal pieces. The pieces look the same. They weigh the same. From the outside, you would never know. From the inside, the gluten network has been crushed and re-knit by force, and the loaf that comes out two days later has a tighter crumb, a paler color, and a flavor that's harder to describe than to miss."],
      ["h3", "What a hand does that a machine doesn't"],
      ["normal", "A baker shaping a boule by hand is doing three things at once: feeling the hydration of the dough, feeling its temperature, and feeling its readiness. Those three signals are not measurable in any way I've found useful. They live in the pads of your fingers, and they get sharper for the first three or four years of shaping."],
      ["blockquote", "You can train someone to read a thermometer in an afternoon. You can't train them to read dough until they've shaped 5,000 loaves."],
      ["normal", "This is why the second-year bakers on our bench shape the same loaves I do, but slower. By year four, they're as fast as I am, and the loaves are indistinguishable. By year six, they're better than me, and I tell them so. The math of patience runs the same direction at every scale."],
      ["h3", "What it costs us"],
      ["normal", "It costs us about 38 cents a loaf, in labor, to do this by hand instead of by machine. Across our 47 cafés and the roughly 9,200 boules we shape weekly, that's a number with commas. It is, by some distance, the most expensive line on our cost-of-goods sheet, and it's the line we will defend last."],
      ["normal", "You're paying for it. We've never been shy about that. The boule is $8.50 and a comparable supermarket loaf is half that. The half is the difference between flour and craft."],
    ]),
  },
  {
    _id: "post-spring-panzanella",
    _type: "post",
    title: "Spring panzanella, six ways",
    slug: slug("spring-panzanella"),
    tag: "Recipe",
    readTime: "4 min",
    publishedAt: "2026-03-28",
    author: "Theo Park, Chef de Cuisine",
    authorRole: "Contributor",
    excerpt:
      "Day-old country sourdough, asparagus, soft-boiled eggs, and a vinaigrette to remember.",
    image: unsplash("photo-1512621776951-a57141f2eefd", 1600, "Spring panzanella"),
    body: portableText("panzanella", [
      ["lede", "Day-old country sourdough, asparagus, soft-boiled eggs, and a vinaigrette to remember. Here's the formula, plus six variations to make it your own."],
      ["normal", "Panzanella is a dish about disrespect. Specifically: disrespecting your bread by tearing it, soaking it, and salting it until it tastes more like a salad than a sandwich. The Tuscan grandmothers who invented it were trying not to throw out yesterday's loaf. We are trying to do exactly the same thing."],
      ["h3", "The base formula"],
      ["normal", "Tear half a loaf of day-old country sourdough into rough thumb-sized chunks. Toss with three tablespoons of olive oil and a pinch of salt. Toast at 400°F for ten minutes — you want crisp on the outside, chewy in the middle. Let cool to room temperature."],
      ["normal", "In a big wide bowl, combine: 1 lb roasted asparagus (you'll want it cooled and cut into bite-length pieces), 4 soft-boiled eggs (halved), a handful of toasted pine nuts, and a generous amount of torn basil. Add the cooled bread. Toss gently with a vinaigrette of 3 parts olive oil, 1 part sherry vinegar, a small spoon of dijon, salt, pepper, and a smashed clove of garlic."],
      ["blockquote", "Let the bowl sit on the counter for ten minutes before you serve it. The bread needs time to drink."],
      ["h3", "Six ways to make it yours"],
      ["normal", "1. Swap asparagus for charred snap peas. 2. Add halved cherry tomatoes — yes, even now, if you can find good ones. 3. Crumble feta on top instead of pine nuts. 4. Use leftover roast chicken instead of eggs. 5. Add thin slices of fennel for crunch. 6. Finish with a drizzle of honey if your vinegar is sharp."],
    ]),
  },
  {
    _id: "post-heritage-mill",
    _type: "post",
    title: "A morning at Heritage Mill",
    slug: slug("heritage-mill"),
    tag: "Field",
    readTime: "6 min",
    publishedAt: "2026-03-15",
    author: "Jules Whitfield",
    authorRole: "Contributor",
    excerpt:
      "Where our wheat comes from, who grows it, and how it ends up in the loaf you ate Tuesday.",
    image: unsplash("photo-1574323347407-f5e1ad6d020b", 1600, "Wheat field at Heritage Mill"),
    body: portableText("mill", [
      ["lede", "Where our wheat comes from, who grows it, and how it ends up in the loaf you ate Tuesday. A morning at Heritage Mill in Logan, Utah."],
      ["normal", "It's still dark when we pull into the lot. Heritage Mill sits on the edge of a field that, in another month, will be planted with hard red winter wheat. For now, it's just brown earth, frost, and the long beam of headlights from a truck pulling in two minutes after us."],
      ["normal", "The miller is named Carl. He's been milling wheat for thirty-one years, and his son Pete now works alongside him. Together they grind 1,800 lbs of our flour every week, plus enough to supply a handful of small bakeries across northern Utah and southern Idaho. They are, by any measure, a small mill."],
      ["h3", "Why a small mill matters"],
      ["normal", "Industrial flour is a blend. It's mixed across hundreds of farms and dozens of varieties, then standardized for protein content, ash, and color. It bakes consistently. It also, by design, tastes like nothing in particular."],
      ["normal", "What Heritage Mill grinds for us is single-variety, single-farm flour, milled to order. The variety is Turkey Red — a heritage hard red wheat that came to North America with Mennonite immigrants in 1873. The farm is Larsen Family, twenty miles east of here. We've been buying from them since 2014."],
      ["blockquote", "Wheat is a place. If you don't know the place, you don't know what your bread is going to taste like."],
      ["normal", "On the way home, I stop for a coffee. The cashier asks where I'm going. I say I just came back from the mill. She nods like she knows what that means."],
    ]),
  },
  {
    _id: "post-revive-baguette",
    _type: "post",
    title: "The right way to revive a baguette",
    slug: slug("revive-baguette"),
    tag: "How-to",
    readTime: "3 min",
    publishedAt: "2026-03-05",
    author: "Inés Marchetti",
    authorRole: "Contributor",
    excerpt: "Forget the toaster. Run it under water, and into the oven. Trust us.",
    image: unsplash("photo-1568254183919-78a4f43a2877", 1600, "Baguettes"),
    body: portableText("baguette", [
      ["lede", "Forget the toaster. Run it under water, and into the oven. Trust us."],
    ]),
  },
  {
    _id: "post-levain-mason-jar",
    _type: "post",
    title: "On keeping a 14-year-old levain alive",
    slug: slug("levain-mason-jar"),
    tag: "Story",
    readTime: "5 min",
    publishedAt: "2026-02-20",
    author: "Inés Marchetti",
    authorRole: "Contributor",
    excerpt:
      "It started in a Mason jar in a Sugar House basement. It hasn't stopped working a day since.",
    image: unsplash("photo-1509440159596-0249088772ff", 1600, "Hearth loaves"),
    body: portableText("levain", [
      ["lede", "It started in a Mason jar in a Sugar House basement. It hasn't stopped working a day since."],
    ]),
  },
  {
    _id: "post-butter-letters",
    _type: "post",
    title: "Letters from the butter rotation",
    slug: slug("butter-letters"),
    tag: "Field",
    readTime: "8 min",
    publishedAt: "2026-02-08",
    author: "Theo Park",
    authorRole: "Contributor",
    excerpt:
      "Why we test six butters every spring, and why this year's pick was the most unlikely one.",
    image: unsplash("photo-1486427944299-d1955d23e34d", 1600, "Pastries"),
    body: portableText("butter", [
      ["lede", "Why we test six butters every spring, and why this year's pick was the most unlikely one."],
    ]),
  },
];
